# Generated by Django 5.0.6 on 2024-05-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_postcomment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='home.postcomment'),
        ),
    ]
